[package]
name = "simple_malware"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.57.0", features = ["Win32", "Win32_Security", "Win32_System", "Win32_System_Memory", "Win32_System_Threading"] }
